version: "3.7"

networks:
  slim-network:
    name: slim-network

services:
  load-balancer:
    image: nginx:mainline-alpine
    container_name: load-balancer
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ./docker/dev/nginx/load-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "29010:80"
    depends_on:
      - app-proxy
    networks:
      - slim-network
  app-proxy:
    image: nginx:mainline-alpine
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - slim-network
  app:
    build:
      dockerfile: ./docker/dev/containers/App.Dockerfile
      context: .
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - slim-network
  redis:
    image: redis:7.0.8-alpine
    restart: unless-stopped
    networks:
      - slim-network